using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class DebugReaderCodegen
{
    // Paths are derived from wherever the registry actually lives so that
    // the user can place it anywhere via the Setup window.
    public static string GetRootFolder()
    {
        var guids = AssetDatabase.FindAssets("t:DebugReaderRegistry");
        if (guids.Length == 0) return null;
        var path = AssetDatabase.GUIDToAssetPath(guids[0]);
        return Path.GetDirectoryName(path).Replace('\\', '/');
    }

    public static string GeneratedFolder   => $"{GetRootFolder()}/Generated/";
    public static string GeneratedFilePath => $"{GetRootFolder()}/Generated/DebugReader.cs";

    // -------------------------------------------------------------------------

    public static void RefreshRegistry(DebugReaderRegistry registry)
    {
        var settings = FindAllSettings();
        registry.SetSettings(settings);
        EditorUtility.SetDirty(registry);
        AssetDatabase.SaveAssetIfDirty(registry);
    }

    public static void GenerateCode()
    {
        var rootFolder = GetRootFolder();
        if (rootFolder == null)
        {
            Debug.LogWarning("[DebugReader] No registry found — run Tools > Debug Reader > Setup first.");
            return;
        }

        var settings = FindAllSettings();

        var sb = new StringBuilder();
        sb.AppendLine("// This file is auto-generated by DebugReaderCodegen. Do not edit manually.");
        sb.AppendLine("// Add or remove Debug Reader assets to update this file.");
        sb.AppendLine();
        sb.AppendLine("#if UNITY_EDITOR");
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();
        sb.AppendLine("public static class DebugReader");
        sb.AppendLine("{");

        var groups = settings
            .GroupBy(s => s.GroupName)
            .OrderBy(g => g.Key);

        foreach (var group in groups)
        {
            var className = Sanitize(group.Key);
            var groupKey  = group.Key;
            sb.AppendLine($"    public static class {className}");
            sb.AppendLine("    {");

            foreach (var setting in group.OrderBy(s => s.SettingName))
            {
                var propName  = Sanitize(setting.SettingName);
                var fieldName = FieldName(propName);
                var key       = setting.FullKey;

                string typeName, returnType, nullValue;
                bool   hasMute;

                if      (setting is DebugReaderBool)    { typeName = "DebugReaderBool";    returnType = "bool";    nullValue = "false";         hasMute = true;  }
                else if (setting is DebugReaderFloat)   { typeName = "DebugReaderFloat";   returnType = "float";   nullValue = "0f";            hasMute = false; }
                else if (setting is DebugReaderColor)   { typeName = "DebugReaderColor";   returnType = "Color";   nullValue = "Color.white";   hasMute = false; }
                else if (setting is DebugReaderVector2) { typeName = "DebugReaderVector2"; returnType = "Vector2"; nullValue = "Vector2.zero";  hasMute = false; }
                else if (setting is DebugReaderVector3) { typeName = "DebugReaderVector3"; returnType = "Vector3"; nullValue = "Vector3.zero";  hasMute = false; }
                else continue;

                sb.AppendLine($"        private static {typeName} {fieldName};");
                sb.AppendLine();
                sb.AppendLine($"        public static {returnType} {propName}");
                sb.AppendLine("        {");
                sb.AppendLine("            get");
                sb.AppendLine("            {");
                sb.AppendLine($"                if (ReferenceEquals({fieldName}, null))");
                sb.AppendLine($"                    {fieldName} = DebugReaderRuntime.Resolve<{typeName}>(\"{key}\");");

                if (hasMute)
                {
                    sb.AppendLine($"                return !ReferenceEquals({fieldName}, null)");
                    sb.AppendLine($"                    && !DebugReaderRuntime.IsGroupMuted(\"{groupKey}\")");
                    sb.AppendLine($"                    && {fieldName}.value;");
                }
                else
                {
                    sb.AppendLine($"                return ReferenceEquals({fieldName}, null) ? {nullValue} : {fieldName}.value;");
                }

                sb.AppendLine("            }");
                sb.AppendLine("        }");
                sb.AppendLine();
            }

            sb.AppendLine("    }");
            sb.AppendLine();
        }

        sb.AppendLine("}");
        sb.AppendLine("#endif");

        var newContent   = sb.ToString();
        var generatedDir = Path.GetDirectoryName(GeneratedFilePath);

        if (!Directory.Exists(generatedDir))
            Directory.CreateDirectory(generatedDir);

        // Skip write+reimport if nothing changed, to avoid a redundant compile cycle.
        if (File.Exists(GeneratedFilePath) && File.ReadAllText(GeneratedFilePath) == newContent)
            return;

        File.WriteAllText(GeneratedFilePath, newContent);
        AssetDatabase.ImportAsset(GeneratedFilePath);
        Debug.Log($"[DebugReader] DebugReader.cs regenerated ({settings.Count} settings across {groups.Count()} groups).");
    }

    // Finds all debug setting assets anywhere under registryFolder and moves any
    // that are not already in [registryFolder]/[GroupName]/ to their correct subfolder.
    public static void OrganizeAssets(string registryFolder)
    {
        var guids = new HashSet<string>();
        foreach (var filter in new[] { "t:DebugReaderBool", "t:DebugReaderFloat", "t:DebugReaderColor", "t:DebugReaderVector2", "t:DebugReaderVector3" })
            foreach (var guid in AssetDatabase.FindAssets(filter, new[] { registryFolder }))
                guids.Add(guid);

        foreach (var guid in guids)
        {
            var path  = AssetDatabase.GUIDToAssetPath(guid);
            var asset = AssetDatabase.LoadAssetAtPath<DebugReaderSettingBase>(path);
            if (asset == null || !asset.FullKey.Contains('.')) continue;

            var expectedFolder = $"{registryFolder}/{asset.GroupName}";
            var expectedPath   = $"{expectedFolder}/{asset.FullKey}.asset";

            if (path == expectedPath) continue;

            if (!AssetDatabase.IsValidFolder(expectedFolder))
                AssetDatabase.CreateFolder(registryFolder, asset.GroupName);

            var error = AssetDatabase.MoveAsset(path, expectedPath);
            if (!string.IsNullOrEmpty(error))
                Debug.LogWarning($"[DebugReader] Could not move '{path}' → '{expectedPath}': {error}");
            else
                Debug.Log($"[DebugReader] Organized '{asset.FullKey}' into {expectedFolder}/");
        }
    }

    // -------------------------------------------------------------------------

    private static List<DebugReaderSettingBase> FindAllSettings()
    {
        var guids = new HashSet<string>();
        foreach (var filter in new[] { "t:DebugReaderBool", "t:DebugReaderFloat", "t:DebugReaderColor", "t:DebugReaderVector2", "t:DebugReaderVector3" })
            foreach (var guid in AssetDatabase.FindAssets(filter))
                guids.Add(guid);

        var results = new List<DebugReaderSettingBase>();
        foreach (var guid in guids)
        {
            var path  = AssetDatabase.GUIDToAssetPath(guid);
            var asset = AssetDatabase.LoadAssetAtPath<DebugReaderSettingBase>(path);
            if (asset != null) results.Add(asset);
        }

        results.Sort((a, b) => string.Compare(a.name, b.name, System.StringComparison.Ordinal));
        return results;
    }

    private static string FieldName(string propName) =>
        propName.Length == 0 ? "_field" : "_" + char.ToLower(propName[0]) + propName.Substring(1);

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder();
        foreach (char c in name)
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        if (sb.Length > 0 && char.IsDigit(sb[0]))
            sb.Insert(0, '_');
        return sb.ToString();
    }
}
