using System.IO;
using UnityEditor;
using UnityEngine;

[InitializeOnLoad]
static class DebugSettingsGitignore
{
    private const string PrefsKey      = "DebugSettings.GitignorePrompted";
    // Referencing the single source of truth in DebugSettingsCodegen
    private static string GitignoreEntry => DebugSettingsCodegen.GeneratedFolder;

    static DebugSettingsGitignore()
    {
        // Reset the pref if the stored entry no longer matches the current path,
        // so the prompt re-appears if the generated folder location ever changes.
        if (EditorPrefs.GetBool(PrefsKey, false))
        {
            var projectRoot   = Path.GetDirectoryName(Application.dataPath);
            var gitignorePath = Path.Combine(projectRoot, ".gitignore");
            if (!File.Exists(gitignorePath) || !File.ReadAllText(gitignorePath).Contains(GitignoreEntry))
                DebugSettingsMenuItems.ResetGitignorePref();
            else
                return;
        }

        // Defer until after domain reload so DisplayDialog is safe to call.
        EditorApplication.delayCall += CheckGitignore;
    }

    private static void CheckGitignore()
    {
        var projectRoot   = Path.GetDirectoryName(Application.dataPath);
        var gitignorePath = Path.Combine(projectRoot, ".gitignore");

        // Already covered — no prompt needed. Don't set the pref so we re-check
        // next session in case the entry is ever removed.
        if (File.Exists(gitignorePath) && File.ReadAllText(gitignorePath).Contains(GitignoreEntry))
            return;

        bool confirm = EditorUtility.DisplayDialog(
            "Debug Settings — .gitignore",
            $"The auto-generated DebugReader.cs is not covered by your .gitignore.\n\n" +
            $"Would you like to add the following entry?\n\n    {GitignoreEntry}\n\n" +
            $"You can always add it manually later.",
            "Add Entry",
            "Skip"
        );

        // Record the decision so this dialog doesn't appear again.
        EditorPrefs.SetBool(PrefsKey, true);

        if (!confirm) return;

        File.AppendAllText(gitignorePath, $"\n# Auto-generated by DebugSettings — safe to delete if you prefer to commit this file\n{GitignoreEntry}\n");
        Debug.LogWarning($"[DebugSettings] Added '{GitignoreEntry}' to .gitignore ({gitignorePath}). Remove the entry manually if you'd prefer to commit the generated file.");
    }
}
